//! Duct-regime classification from a refractivity profile.
//!
//! Given a refractivity gradient `dN/dh` (N-units per kilometre) and a few
//! ancillary surface variables, this module decides which propagation
//! regime an atmosphere is in:
//!
//! 1. **Standard / normal**: `dN/dh ≥ -40 N/km` — refraction is captured
//!    by the 4/3-Earth k-factor; no anomalous propagation.
//! 2. **Super-refractive**: `dN/dh ∈ [-157, -40] N/km` — rays bend more
//!    sharply downward than under standard refraction but are not
//!    *trapped*. From the [`super::ducting_horizon`] perspective this
//!    extends the horizon modestly; the regime itself is still
//!    [`DuctRegime::None`] (no closed duct boundary).
//! 3. **Surface duct (trapping)**: `dN/dh < -157 N/km` and `k > 2` — the
//!    M-profile reverses (`dM/dh < 0`) and rays launched at near-zero
//!    elevation get trapped between the surface and a "duct top". Surface
//!    ducts most commonly arise from a strong temperature inversion or
//!    a marine humidity gradient and typically have layer thicknesses
//!    of 25–100 m. The height returned scales linearly with the depth
//!    of the trapping gradient (steeper gradient ⇒ thicker layer up to
//!    the published 25–100 m envelope).
//! 4. **Evaporation duct (marine)**: warm-sea surface humidity in the
//!    `(0.7, 0.95)` range produces a sharply non-linear humidity profile
//!    over the first ~10–40 m above the sea surface. The resulting
//!    `dM/dh` reverses inside that layer even when the bulk gradient
//!    above looks normal. We use the Paulus/Jeske parameterisation of
//!    evaporation-duct height as a function of relative humidity:
//!    `h_dz ≈ 5 + 35·(0.85 - RH)` m for `RH ∈ (0.5, 0.85)` (typical
//!    open-ocean values; the curve is monotonic decreasing in RH because
//!    a drier sea surface produces a steeper humidity discontinuity and
//!    a deeper trapping layer).
//! 5. **Elevated duct**: a trapping layer aloft (typical 500–2000 m
//!    base, ~100 m thickness) that traps elevated emitters but leaves
//!    surface emitters un-affected — and conversely *blocks* surface
//!    radars from seeing above-duct targets. Selected by callers that
//!    have an explicit elevated-layer profile; this module exposes the
//!    enum variant but the bulk-gradient classifier emits surface and
//!    evaporation regimes only (the only ones inferable from
//!    `(dN/dh, k, RH)` alone).
//!
//! # References
//!
//! - ITU-R Recommendation P.453-14 (2019), §2, §4 — gradient thresholds
//!   for standard, super-refractive, and trapping conditions; surface
//!   duct M-unit signature.
//! - Skolnik, *Introduction to Radar Systems*, 3rd ed. (2001), §2.10
//!   (anomalous propagation) — operational summaries of the four
//!   regimes and their detection-range consequences.
//! - Hitney, *Refractive Effects from VHF to EHF, Part B: Propagation
//!   Effects* (Naval Postgraduate School / NRL lecture notes, 1992) —
//!   surface-duct depth vs gradient steepness, evaporation-duct height
//!   vs surface humidity tabulations.
//! - Paulus (1985), *Practical Application of an Evaporation Duct Model*,
//!   Radio Science 20(4) — origin of the linear humidity → duct-height
//!   parameterisation used below.
//! - Hitney & Vieth (1990), *Statistical Assessment of Evaporation Duct
//!   Propagation*, IEEE Trans. Ant. Prop. 38(6) — open-ocean duct-height
//!   statistics 5–40 m range.

/// Classified atmospheric duct regime returned by
/// [`classify_duct_regime`] and consumed by
/// [`super::ducting_horizon::ducting_horizon_range_m`].
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum DuctRegime {
    /// No duct present. Either the standard 4/3-Earth atmosphere or the
    /// non-trapping super-refractive regime — both are handled by the
    /// usual [`crate::propagation::min_target_altitude_for_los_m`]
    /// horizon formula without anomalous extension.
    None,

    /// Surface-based trapping duct. Rays launched horizontally are
    /// trapped between the surface and the duct top at `height_m`.
    /// Typical values 25-100 m over land (strong inversion) or warmer
    /// over sea.
    Surface {
        /// Duct-top height above the surface in metres.
        height_m: f64,
    },

    /// Elevated trapping layer. Rays inside the layer (between `base_m`
    /// and `top_m`) are trapped; surface-launched rays travel
    /// underneath, and ground radars cannot see targets *above* the
    /// duct (the trapping layer acts as a one-sided mirror).
    Elevated {
        /// Layer bottom altitude (m).
        base_m: f64,
        /// Layer top altitude (m).
        top_m: f64,
    },

    /// Marine evaporation duct. The trapping layer is the first
    /// `height_m` metres above warm-sea surface and is generated by the
    /// near-discontinuous humidity profile. Typical 5-40 m.
    Evaporation {
        /// Evaporation-duct height above sea level (m).
        height_m: f64,
    },
}

/// Refractivity gradient threshold (N/km) above which the atmosphere is
/// considered standard or only mildly super-refractive — no anomalous
/// propagation. Per ITU-R P.453-14 §4, the canonical value is
/// `-40 N/km`.
pub const STANDARD_GRADIENT_THRESHOLD_N_PER_KM: f64 = -40.0;

/// Trapping-gradient threshold (N/km). Below this value the modified
/// refractivity `M(h)` actually decreases with altitude, i.e. the
/// atmosphere supports surface trapping. Per Skolnik §2.10, the
/// canonical value is `-157 N/km` (the gradient at which `dM/dh = 0`).
pub const TRAPPING_GRADIENT_THRESHOLD_N_PER_KM: f64 = -157.0;

/// Minimum effective-Earth `k`-factor at which trapping is robust enough
/// to be classified as a surface duct (gradients between -157 N/km and
/// strong trapping can sometimes correspond to weak surface ducts that
/// the k-factor amplifies into proper trapping).
pub const SURFACE_DUCT_MIN_K_FACTOR: f64 = 2.0;

/// Lower bound of the open-ocean relative-humidity range in which the
/// Paulus/Jeske evaporation-duct parameterisation is valid.
pub const EVAPORATION_DUCT_MIN_RH: f64 = 0.7;

/// Upper bound — above this relative humidity the surface humidity
/// discontinuity is too small to support a duct.
pub const EVAPORATION_DUCT_MAX_RH: f64 = 0.95;

/// Classify the propagation regime from a surface-gradient triple.
///
/// `refractivity_gradient_n_per_km` is the bulk lower-troposphere
/// `dN/dh` in N-units per kilometre (negative for downward-decreasing
/// refractivity, the usual case). `k_factor_earth` is the effective
/// Earth radius factor — typically `4/3` for standard atmosphere but
/// can climb above 2 inside duct layers. `surface_humidity` is the
/// near-surface relative humidity (0-1 fraction).
///
/// Decision order matters: surface trapping is checked first (it is the
/// dominant regime for a sufficiently negative gradient), then the
/// evaporation-duct branch (marine warm-sea ducts that can coexist with
/// otherwise normal bulk gradients).
///
/// Elevated ducts cannot be inferred from a single bulk-gradient
/// summary; callers that have a layered profile should construct the
/// `DuctRegime::Elevated` variant directly.
pub fn classify_duct_regime(
    refractivity_gradient_n_per_km: f64,
    k_factor_earth: f64,
    surface_humidity: f64,
) -> DuctRegime {
    // 1. Surface duct (trapping). Per Skolnik §2.10 + ITU-R P.453-14
    //    §4, this requires a gradient steeper than -157 N/km and an
    //    effective-Earth amplification factor > 2 to be classified as a
    //    robust surface duct (weaker trapping below k = 2 typically
    //    presents as super-refraction only).
    if refractivity_gradient_n_per_km < TRAPPING_GRADIENT_THRESHOLD_N_PER_KM
        && k_factor_earth > SURFACE_DUCT_MIN_K_FACTOR
    {
        // Duct depth scales (roughly linearly) with how far below the
        // -157 N/km threshold the gradient sits. Operational tables
        // (Hitney 1992 fig 6, AREPS handbook fig 4-3) bound layer
        // depths to the 25-100 m envelope for "moderate" trapping;
        // extreme cases (-400 N/km, e.g. strong subsidence inversion)
        // can reach 150-200 m but those are out-of-envelope and we
        // clamp at 150 m.
        let depth = surface_duct_depth_m(refractivity_gradient_n_per_km);
        return DuctRegime::Surface { height_m: depth };
    }

    // 2. Marine evaporation duct (Paulus 1985 / Hitney & Vieth 1990).
    //    Driven by the near-surface humidity discontinuity; classified
    //    from RH alone since the bulk gradient above the duct layer is
    //    typically normal.
    if surface_humidity > EVAPORATION_DUCT_MIN_RH
        && surface_humidity < EVAPORATION_DUCT_MAX_RH
    {
        let height = evaporation_duct_height_m(surface_humidity);
        return DuctRegime::Evaporation { height_m: height };
    }

    // 3. Otherwise — standard atmosphere or non-trapping
    //    super-refraction. The 4/3-Earth horizon formula handles both.
    DuctRegime::None
}

/// Surface-duct top height (m) parameterised by gradient steepness.
///
/// Linear interpolation between the canonical AREPS handbook anchors:
/// at the trapping threshold (-157 N/km) the duct just barely forms
/// (~25 m), and at a strong-trapping reference of -400 N/km the layer
/// reaches its published upper bound of ~100 m. Hard-clamped to
/// `[25, 150]` m so adversarial inputs don't blow up the horizon.
fn surface_duct_depth_m(gradient_n_per_km: f64) -> f64 {
    const WEAK_GRADIENT: f64 = -157.0;
    const STRONG_GRADIENT: f64 = -400.0;
    const WEAK_DEPTH_M: f64 = 25.0;
    const STRONG_DEPTH_M: f64 = 100.0;

    let g = gradient_n_per_km.clamp(STRONG_GRADIENT, WEAK_GRADIENT);
    let t = (WEAK_GRADIENT - g) / (WEAK_GRADIENT - STRONG_GRADIENT);
    let depth = WEAK_DEPTH_M + t * (STRONG_DEPTH_M - WEAK_DEPTH_M);
    depth.clamp(25.0, 150.0)
}

/// Evaporation-duct height (m) from near-surface relative humidity per
/// the Paulus (1985) linear parameterisation `h_dz ≈ 5 + 35·(0.85 - RH)`
/// — drier surfaces produce steeper humidity gradients and deeper
/// ducts. Clamped to the open-ocean envelope `[5, 40]` m
/// (Hitney & Vieth 1990).
fn evaporation_duct_height_m(surface_humidity: f64) -> f64 {
    let rh = surface_humidity.clamp(EVAPORATION_DUCT_MIN_RH, EVAPORATION_DUCT_MAX_RH);
    let h = 5.0 + 35.0 * (0.85 - rh);
    h.clamp(5.0, 40.0)
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Standard atmosphere gradient (-40 N/km) ⇒ no duct.
    #[test]
    fn standard_atmosphere_returns_none() {
        let regime = classify_duct_regime(-40.0, 4.0 / 3.0, 0.5);
        assert_eq!(regime, DuctRegime::None);
    }

    /// Super-refractive but non-trapping (-100 N/km) ⇒ no duct
    /// (handled by k-factor refraction, not by an explicit duct).
    #[test]
    fn super_refractive_returns_none() {
        let regime = classify_duct_regime(-100.0, 1.5, 0.5);
        assert_eq!(regime, DuctRegime::None);
    }

    /// Trapping gradient (-200 N/km) with amplified k-factor ⇒ surface
    /// duct. Depth should fall within the published 25-100 m envelope.
    #[test]
    fn strong_trapping_returns_surface_duct() {
        let regime = classify_duct_regime(-200.0, 2.5, 0.5);
        match regime {
            DuctRegime::Surface { height_m } => {
                assert!(
                    (25.0..=100.0).contains(&height_m),
                    "surface duct height {height_m} m outside 25-100 m envelope"
                );
            }
            other => panic!("expected Surface duct, got {other:?}"),
        }
    }

    /// Trapping gradient at -157 N/km is right at the threshold; just
    /// below it (e.g. -158) should classify as Surface; just above
    /// (-156) should be None. Pin both edges.
    #[test]
    fn trapping_threshold_edge_behaviour() {
        let just_above = classify_duct_regime(-156.0, 2.5, 0.5);
        assert_eq!(just_above, DuctRegime::None);
        let just_below = classify_duct_regime(-158.0, 2.5, 0.5);
        assert!(matches!(just_below, DuctRegime::Surface { .. }));
    }

    /// Trapping gradient WITHOUT amplified k-factor (k = 4/3) ⇒ should
    /// still return None — robust surface ducts require k > 2.
    #[test]
    fn trapping_gradient_low_k_returns_none() {
        let regime = classify_duct_regime(-200.0, 4.0 / 3.0, 0.5);
        assert_eq!(regime, DuctRegime::None);
    }

    /// Marine humidity 0.78 (typical warm sea) ⇒ evaporation duct
    /// height in the 7-12 m range per Paulus/Hitney tables.
    #[test]
    fn marine_humidity_returns_evaporation_duct() {
        let regime = classify_duct_regime(-40.0, 4.0 / 3.0, 0.78);
        match regime {
            DuctRegime::Evaporation { height_m } => {
                assert!(
                    (7.0..=12.0).contains(&height_m),
                    "evaporation duct height {height_m} m outside 7-12 m for RH=0.78"
                );
            }
            other => panic!("expected Evaporation duct, got {other:?}"),
        }
    }

    /// Very humid surface (RH = 0.97) ⇒ above the evaporation-duct
    /// upper bound, no duct.
    #[test]
    fn very_humid_returns_none() {
        let regime = classify_duct_regime(-40.0, 4.0 / 3.0, 0.97);
        assert_eq!(regime, DuctRegime::None);
    }

    /// Dry desert surface (RH = 0.2) ⇒ below the evaporation-duct
    /// lower bound, no duct.
    #[test]
    fn dry_surface_returns_none() {
        let regime = classify_duct_regime(-40.0, 4.0 / 3.0, 0.2);
        assert_eq!(regime, DuctRegime::None);
    }

    /// Evaporation-duct height is monotonically decreasing in RH across
    /// the valid envelope (drier ⇒ deeper duct).
    #[test]
    fn evaporation_duct_height_monotonic_in_rh() {
        let h_low = evaporation_duct_height_m(0.72);
        let h_high = evaporation_duct_height_m(0.92);
        assert!(
            h_low > h_high,
            "expected drier RH to give deeper duct: h(0.72)={h_low} h(0.92)={h_high}"
        );
    }

    /// Surface-duct depth is monotonically increasing in gradient
    /// steepness (more negative gradient ⇒ thicker layer).
    #[test]
    fn surface_duct_depth_monotonic_in_gradient() {
        let d_weak = surface_duct_depth_m(-160.0);
        let d_strong = surface_duct_depth_m(-300.0);
        assert!(
            d_strong > d_weak,
            "expected steeper gradient to give deeper duct: weak={d_weak} strong={d_strong}"
        );
    }

    /// Construction of an Elevated duct variant works as documented
    /// (callers with layered profiles build it directly; the classifier
    /// never returns it).
    #[test]
    fn elevated_duct_variant_constructible() {
        let elev = DuctRegime::Elevated {
            base_m: 800.0,
            top_m: 1000.0,
        };
        match elev {
            DuctRegime::Elevated { base_m, top_m } => {
                assert!(top_m > base_m);
            }
            _ => panic!("Elevated variant should be constructible"),
        }
    }
}
