//! Studio endpoint that exposes the parametric mesh generators from
//! `echoforge-world::mesh` as on-demand HTTP responses.
//!
//! Two routes are exposed:
//!
//! - `GET /api/mesh/list` -> JSON [`MeshListResponse`] enumerating the
//!   primitive ids the studio can produce plus the default parameters used
//!   when the client does not override them.
//! - `GET /api/mesh/{primitive}` -> binary STL bytes (`Content-Type:
//!   model/stl`) generated by the matching `echoforge-world::mesh::*_mesh`
//!   generator. Query parameters are interpreted per primitive:
//!     - `sphere`:    `radius`, `n_lat`, `n_lon`
//!     - `plate`:     `width`, `height`, `n_w`, `n_h`
//!     - `cylinder`:  `radius`, `length`, `n_circ`, `n_axial`
//!     - `dihedral`:  `side`, `n`
//!     - `trihedral`: `side`, `n`
//!
//! All parameters have sensible studio-shell defaults so the React mesh
//! viewer can drop in `/api/mesh/sphere` with no query string and get a
//! visualizable STL.
//!
//! The endpoint is strictly read-only and synthesizes meshes in-process; it
//! does not touch any campaign output or repo asset.

use axum::extract::{Path as AxumPath, Query};
use axum::http::{header, HeaderMap, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::{Json, Router};
use echoforge_world::mesh::{
    cylinder_mesh, dihedral_mesh, encode_binary_stl, plate_mesh, sphere_mesh, trihedral_mesh,
    ParametricMesh,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Stable list of primitives this endpoint can render. Order is part of the
/// public contract -- clients rely on it for stable dropdown layout.
pub const PRIMITIVE_IDS: [&str; 5] = ["sphere", "plate", "cylinder", "dihedral", "trihedral"];

/// Conservative tessellation defaults: small enough to render fast in the
/// browser, large enough that the lateral surface looks curved.
const DEFAULT_SPHERE_RADIUS: f64 = 1.0;
const DEFAULT_SPHERE_N_LAT: usize = 24;
const DEFAULT_SPHERE_N_LON: usize = 48;

const DEFAULT_PLATE_WIDTH: f64 = 1.0;
const DEFAULT_PLATE_HEIGHT: f64 = 1.0;
const DEFAULT_PLATE_N_W: usize = 8;
const DEFAULT_PLATE_N_H: usize = 8;

const DEFAULT_CYL_RADIUS: f64 = 0.5;
const DEFAULT_CYL_LENGTH: f64 = 2.0;
const DEFAULT_CYL_N_CIRC: usize = 32;
const DEFAULT_CYL_N_AXIAL: usize = 4;

const DEFAULT_DIHEDRAL_SIDE: f64 = 1.0;
const DEFAULT_DIHEDRAL_N: usize = 8;

const DEFAULT_TRIHEDRAL_SIDE: f64 = 1.0;
const DEFAULT_TRIHEDRAL_N: usize = 8;

/// Maximum number of sample points any single dimension may request. Bounds
/// the worst-case triangle count an unauthenticated caller can ask the
/// studio to synthesize.
const MAX_SAMPLES: usize = 256;

// ---------------------------------------------------------------------------
// JSON contract: GET /api/mesh/list
// ---------------------------------------------------------------------------

/// One entry in the [`MeshListResponse`]: primitive slug, human-readable
/// label, defaults map. `defaults` keys are the *exact* query-parameter
/// names accepted by `/api/mesh/{primitive}` for that primitive (so the UI
/// can render a form by iterating the map).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MeshDescriptor {
    pub primitive_id: String,
    pub display_name: String,
    pub defaults: BTreeMap<String, f64>,
}

/// Response shape for `GET /api/mesh/list`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MeshListResponse {
    pub primitives: Vec<MeshDescriptor>,
}

impl MeshListResponse {
    /// Build the canonical descriptor list. Order matches [`PRIMITIVE_IDS`].
    pub fn canonical() -> Self {
        let primitives = PRIMITIVE_IDS
            .iter()
            .map(|id| descriptor_for(id).expect("PRIMITIVE_IDS only contains known primitives"))
            .collect();
        Self { primitives }
    }
}

fn descriptor_for(primitive: &str) -> Option<MeshDescriptor> {
    let mut defaults = BTreeMap::new();
    let (display, defaults) = match primitive {
        "sphere" => {
            defaults.insert("radius".to_string(), DEFAULT_SPHERE_RADIUS);
            defaults.insert("n_lat".to_string(), DEFAULT_SPHERE_N_LAT as f64);
            defaults.insert("n_lon".to_string(), DEFAULT_SPHERE_N_LON as f64);
            ("Sphere", defaults)
        }
        "plate" => {
            defaults.insert("width".to_string(), DEFAULT_PLATE_WIDTH);
            defaults.insert("height".to_string(), DEFAULT_PLATE_HEIGHT);
            defaults.insert("n_w".to_string(), DEFAULT_PLATE_N_W as f64);
            defaults.insert("n_h".to_string(), DEFAULT_PLATE_N_H as f64);
            ("Plate", defaults)
        }
        "cylinder" => {
            defaults.insert("radius".to_string(), DEFAULT_CYL_RADIUS);
            defaults.insert("length".to_string(), DEFAULT_CYL_LENGTH);
            defaults.insert("n_circ".to_string(), DEFAULT_CYL_N_CIRC as f64);
            defaults.insert("n_axial".to_string(), DEFAULT_CYL_N_AXIAL as f64);
            ("Cylinder", defaults)
        }
        "dihedral" => {
            defaults.insert("side".to_string(), DEFAULT_DIHEDRAL_SIDE);
            defaults.insert("n".to_string(), DEFAULT_DIHEDRAL_N as f64);
            ("Dihedral corner reflector", defaults)
        }
        "trihedral" => {
            defaults.insert("side".to_string(), DEFAULT_TRIHEDRAL_SIDE);
            defaults.insert("n".to_string(), DEFAULT_TRIHEDRAL_N as f64);
            ("Trihedral corner reflector", defaults)
        }
        _ => return None,
    };
    Some(MeshDescriptor {
        primitive_id: primitive.to_string(),
        display_name: display.to_string(),
        defaults,
    })
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum MeshServeError {
    UnknownPrimitive(String),
    InvalidParameter { name: &'static str, message: String },
}

impl std::fmt::Display for MeshServeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownPrimitive(p) => write!(f, "unknown mesh primitive: {p}"),
            Self::InvalidParameter { name, message } => {
                write!(f, "invalid query parameter `{name}`: {message}")
            }
        }
    }
}

impl std::error::Error for MeshServeError {}

impl IntoResponse for MeshServeError {
    fn into_response(self) -> Response {
        let (status, kind) = match &self {
            Self::UnknownPrimitive(_) => (StatusCode::NOT_FOUND, "unknown_primitive"),
            Self::InvalidParameter { .. } => (StatusCode::BAD_REQUEST, "invalid_parameter"),
        };
        let body = Json(serde_json::json!({
            "service": super::DEFAULT_SERVICE_NAME,
            "status": "error",
            "error": kind,
            "message": self.to_string(),
        }));
        (status, body).into_response()
    }
}

// ---------------------------------------------------------------------------
// Query-parameter parsing
// ---------------------------------------------------------------------------

/// Raw query map for the mesh endpoint. Each primitive uses what it needs
/// and ignores the rest, mirroring `serde(deny_unknown_fields = false)`.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct MeshParams {
    pub radius: Option<f64>,
    pub length: Option<f64>,
    pub width: Option<f64>,
    pub height: Option<f64>,
    pub side: Option<f64>,
    pub n_lat: Option<usize>,
    pub n_lon: Option<usize>,
    pub n_w: Option<usize>,
    pub n_h: Option<usize>,
    pub n_circ: Option<usize>,
    pub n_axial: Option<usize>,
    pub n: Option<usize>,
}

fn require_positive(name: &'static str, value: f64) -> Result<f64, MeshServeError> {
    if !(value.is_finite() && value > 0.0) {
        return Err(MeshServeError::InvalidParameter {
            name,
            message: format!("must be a positive finite number, got {value}"),
        });
    }
    Ok(value)
}

fn require_at_least(name: &'static str, value: usize, min: usize) -> Result<usize, MeshServeError> {
    if value < min {
        return Err(MeshServeError::InvalidParameter {
            name,
            message: format!("must be >= {min}, got {value}"),
        });
    }
    if value > MAX_SAMPLES {
        return Err(MeshServeError::InvalidParameter {
            name,
            message: format!("must be <= {MAX_SAMPLES}, got {value}"),
        });
    }
    Ok(value)
}

// ---------------------------------------------------------------------------
// Mesh dispatch
// ---------------------------------------------------------------------------

/// Build the [`ParametricMesh`] for `primitive`, validating query parameters
/// and applying the canonical studio defaults for anything the caller did
/// not provide.
pub fn build_mesh(primitive: &str, params: &MeshParams) -> Result<ParametricMesh, MeshServeError> {
    match primitive {
        "sphere" => {
            let radius =
                require_positive("radius", params.radius.unwrap_or(DEFAULT_SPHERE_RADIUS))?;
            let n_lat = require_at_least("n_lat", params.n_lat.unwrap_or(DEFAULT_SPHERE_N_LAT), 2)?;
            let n_lon = require_at_least("n_lon", params.n_lon.unwrap_or(DEFAULT_SPHERE_N_LON), 3)?;
            Ok(sphere_mesh(radius, n_lat, n_lon))
        }
        "plate" => {
            let width = require_positive("width", params.width.unwrap_or(DEFAULT_PLATE_WIDTH))?;
            let height = require_positive("height", params.height.unwrap_or(DEFAULT_PLATE_HEIGHT))?;
            let n_w = require_at_least("n_w", params.n_w.unwrap_or(DEFAULT_PLATE_N_W), 2)?;
            let n_h = require_at_least("n_h", params.n_h.unwrap_or(DEFAULT_PLATE_N_H), 2)?;
            Ok(plate_mesh(width, height, n_w, n_h))
        }
        "cylinder" => {
            let radius = require_positive("radius", params.radius.unwrap_or(DEFAULT_CYL_RADIUS))?;
            let length = require_positive("length", params.length.unwrap_or(DEFAULT_CYL_LENGTH))?;
            let n_circ =
                require_at_least("n_circ", params.n_circ.unwrap_or(DEFAULT_CYL_N_CIRC), 3)?;
            let n_axial =
                require_at_least("n_axial", params.n_axial.unwrap_or(DEFAULT_CYL_N_AXIAL), 2)?;
            Ok(cylinder_mesh(radius, length, n_circ, n_axial))
        }
        "dihedral" => {
            let side = require_positive("side", params.side.unwrap_or(DEFAULT_DIHEDRAL_SIDE))?;
            let n = require_at_least("n", params.n.unwrap_or(DEFAULT_DIHEDRAL_N), 2)?;
            Ok(dihedral_mesh(side, n))
        }
        "trihedral" => {
            let side = require_positive("side", params.side.unwrap_or(DEFAULT_TRIHEDRAL_SIDE))?;
            let n = require_at_least("n", params.n.unwrap_or(DEFAULT_TRIHEDRAL_N), 2)?;
            Ok(trihedral_mesh(side, n))
        }
        other => Err(MeshServeError::UnknownPrimitive(other.to_string())),
    }
}

// ---------------------------------------------------------------------------
// Axum handlers
// ---------------------------------------------------------------------------

pub async fn mesh_list_handler() -> Json<MeshListResponse> {
    Json(MeshListResponse::canonical())
}

pub async fn mesh_stl_handler(
    AxumPath(primitive): AxumPath<String>,
    Query(params): Query<MeshParams>,
) -> Result<Response, MeshServeError> {
    let mesh = build_mesh(&primitive, &params)?;
    let stl = encode_binary_stl(&mesh);
    let mut headers = HeaderMap::new();
    headers.insert(header::CONTENT_TYPE, HeaderValue::from_static("model/stl"));
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=300"),
    );
    if let Ok(value) = HeaderValue::from_str(&mesh.primitive_id) {
        headers.insert("x-echoforge-primitive", value);
    }
    if let Ok(value) = HeaderValue::from_str(&mesh.triangle_count().to_string()) {
        headers.insert("x-echoforge-triangle-count", value);
    }
    Ok((StatusCode::OK, headers, stl).into_response())
}

// ---------------------------------------------------------------------------
// Router builder
// ---------------------------------------------------------------------------

/// Sub-router that exposes the mesh-serve endpoints. Designed to be
/// `.merge()`'d into the studio's top-level router (mirrors the
/// `traceability` sub-router pattern).
pub fn mesh_router() -> Router {
    Router::new()
        .route("/api/mesh/list", get(mesh_list_handler))
        .route("/api/mesh/{primitive}", get(mesh_stl_handler))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
#[path = "mesh_serve_tests.rs"]
mod tests;
