//! Studio endpoint that exposes the parametric mesh generators from
//! `echoforge-world::mesh` as on-demand HTTP responses.
//!
//! Two routes are exposed:
//!
//! - `GET /api/mesh/list` -> JSON [`MeshListResponse`] enumerating the
//!   primitive ids the studio can produce plus the default parameters used
//!   when the client does not override them.
//! - `GET /api/mesh/{primitive}` -> binary STL bytes (`Content-Type:
//!   model/stl`) generated by the matching `echoforge-world::mesh::*_mesh`
//!   generator. Query parameters are interpreted per primitive:
//!     - `sphere`:    `radius`, `n_lat`, `n_lon`
//!     - `plate`:     `width`, `height`, `n_w`, `n_h`
//!     - `cylinder`:  `radius`, `length`, `n_circ`, `n_axial`
//!     - `dihedral`:  `side`, `n`
//!     - `trihedral`: `side`, `n`
//!
//! All parameters have sensible studio-shell defaults so the React mesh
//! viewer can drop in `/api/mesh/sphere` with no query string and get a
//! visualizable STL.
//!
//! The endpoint is strictly read-only and synthesizes meshes in-process; it
//! does not touch any campaign output or repo asset.

use axum::extract::{Path as AxumPath, Query};
use axum::http::{header, HeaderMap, HeaderValue, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::get;
use axum::{Json, Router};
use echoforge_world::mesh::{
    cylinder_mesh, dihedral_mesh, encode_binary_stl, plate_mesh, sphere_mesh, trihedral_mesh,
    ParametricMesh,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Stable list of primitives this endpoint can render. Order is part of the
/// public contract -- clients rely on it for stable dropdown layout.
pub const PRIMITIVE_IDS: [&str; 5] = ["sphere", "plate", "cylinder", "dihedral", "trihedral"];

/// Conservative tessellation defaults: small enough to render fast in the
/// browser, large enough that the lateral surface looks curved.
const DEFAULT_SPHERE_RADIUS: f64 = 1.0;
const DEFAULT_SPHERE_N_LAT: usize = 24;
const DEFAULT_SPHERE_N_LON: usize = 48;

const DEFAULT_PLATE_WIDTH: f64 = 1.0;
const DEFAULT_PLATE_HEIGHT: f64 = 1.0;
const DEFAULT_PLATE_N_W: usize = 8;
const DEFAULT_PLATE_N_H: usize = 8;

const DEFAULT_CYL_RADIUS: f64 = 0.5;
const DEFAULT_CYL_LENGTH: f64 = 2.0;
const DEFAULT_CYL_N_CIRC: usize = 32;
const DEFAULT_CYL_N_AXIAL: usize = 4;

const DEFAULT_DIHEDRAL_SIDE: f64 = 1.0;
const DEFAULT_DIHEDRAL_N: usize = 8;

const DEFAULT_TRIHEDRAL_SIDE: f64 = 1.0;
const DEFAULT_TRIHEDRAL_N: usize = 8;

/// Maximum number of sample points any single dimension may request. Bounds
/// the worst-case triangle count an unauthenticated caller can ask the
/// studio to synthesize.
const MAX_SAMPLES: usize = 256;

// ---------------------------------------------------------------------------
// JSON contract: GET /api/mesh/list
// ---------------------------------------------------------------------------

/// One entry in the [`MeshListResponse`]: primitive slug, human-readable
/// label, defaults map. `defaults` keys are the *exact* query-parameter
/// names accepted by `/api/mesh/{primitive}` for that primitive (so the UI
/// can render a form by iterating the map).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MeshDescriptor {
    pub primitive_id: String,
    pub display_name: String,
    pub defaults: BTreeMap<String, f64>,
}

/// Response shape for `GET /api/mesh/list`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MeshListResponse {
    pub primitives: Vec<MeshDescriptor>,
}

impl MeshListResponse {
    /// Build the canonical descriptor list. Order matches [`PRIMITIVE_IDS`].
    pub fn canonical() -> Self {
        let primitives = PRIMITIVE_IDS
            .iter()
            .map(|id| descriptor_for(id).expect("PRIMITIVE_IDS only contains known primitives"))
            .collect();
        Self { primitives }
    }
}

fn descriptor_for(primitive: &str) -> Option<MeshDescriptor> {
    let mut defaults = BTreeMap::new();
    let (display, defaults) = match primitive {
        "sphere" => {
            defaults.insert("radius".to_string(), DEFAULT_SPHERE_RADIUS);
            defaults.insert("n_lat".to_string(), DEFAULT_SPHERE_N_LAT as f64);
            defaults.insert("n_lon".to_string(), DEFAULT_SPHERE_N_LON as f64);
            ("Sphere", defaults)
        }
        "plate" => {
            defaults.insert("width".to_string(), DEFAULT_PLATE_WIDTH);
            defaults.insert("height".to_string(), DEFAULT_PLATE_HEIGHT);
            defaults.insert("n_w".to_string(), DEFAULT_PLATE_N_W as f64);
            defaults.insert("n_h".to_string(), DEFAULT_PLATE_N_H as f64);
            ("Plate", defaults)
        }
        "cylinder" => {
            defaults.insert("radius".to_string(), DEFAULT_CYL_RADIUS);
            defaults.insert("length".to_string(), DEFAULT_CYL_LENGTH);
            defaults.insert("n_circ".to_string(), DEFAULT_CYL_N_CIRC as f64);
            defaults.insert("n_axial".to_string(), DEFAULT_CYL_N_AXIAL as f64);
            ("Cylinder", defaults)
        }
        "dihedral" => {
            defaults.insert("side".to_string(), DEFAULT_DIHEDRAL_SIDE);
            defaults.insert("n".to_string(), DEFAULT_DIHEDRAL_N as f64);
            ("Dihedral corner reflector", defaults)
        }
        "trihedral" => {
            defaults.insert("side".to_string(), DEFAULT_TRIHEDRAL_SIDE);
            defaults.insert("n".to_string(), DEFAULT_TRIHEDRAL_N as f64);
            ("Trihedral corner reflector", defaults)
        }
        _ => return None,
    };
    Some(MeshDescriptor {
        primitive_id: primitive.to_string(),
        display_name: display.to_string(),
        defaults,
    })
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub enum MeshServeError {
    UnknownPrimitive(String),
    InvalidParameter { name: &'static str, message: String },
}

impl std::fmt::Display for MeshServeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownPrimitive(p) => write!(f, "unknown mesh primitive: {p}"),
            Self::InvalidParameter { name, message } => {
                write!(f, "invalid query parameter `{name}`: {message}")
            }
        }
    }
}

impl std::error::Error for MeshServeError {}

impl IntoResponse for MeshServeError {
    fn into_response(self) -> Response {
        let (status, kind) = match &self {
            Self::UnknownPrimitive(_) => (StatusCode::NOT_FOUND, "unknown_primitive"),
            Self::InvalidParameter { .. } => (StatusCode::BAD_REQUEST, "invalid_parameter"),
        };
        let body = Json(serde_json::json!({
            "service": super::DEFAULT_SERVICE_NAME,
            "status": "error",
            "error": kind,
            "message": self.to_string(),
        }));
        (status, body).into_response()
    }
}

// ---------------------------------------------------------------------------
// Query-parameter parsing
// ---------------------------------------------------------------------------

/// Raw query map for the mesh endpoint. Each primitive uses what it needs
/// and ignores the rest, mirroring `serde(deny_unknown_fields = false)`.
#[derive(Debug, Clone, Default, Deserialize)]
pub struct MeshParams {
    pub radius: Option<f64>,
    pub length: Option<f64>,
    pub width: Option<f64>,
    pub height: Option<f64>,
    pub side: Option<f64>,
    pub n_lat: Option<usize>,
    pub n_lon: Option<usize>,
    pub n_w: Option<usize>,
    pub n_h: Option<usize>,
    pub n_circ: Option<usize>,
    pub n_axial: Option<usize>,
    pub n: Option<usize>,
}

fn require_positive(name: &'static str, value: f64) -> Result<f64, MeshServeError> {
    if !(value.is_finite() && value > 0.0) {
        return Err(MeshServeError::InvalidParameter {
            name,
            message: format!("must be a positive finite number, got {value}"),
        });
    }
    Ok(value)
}

fn require_at_least(name: &'static str, value: usize, min: usize) -> Result<usize, MeshServeError> {
    if value < min {
        return Err(MeshServeError::InvalidParameter {
            name,
            message: format!("must be >= {min}, got {value}"),
        });
    }
    if value > MAX_SAMPLES {
        return Err(MeshServeError::InvalidParameter {
            name,
            message: format!("must be <= {MAX_SAMPLES}, got {value}"),
        });
    }
    Ok(value)
}

// ---------------------------------------------------------------------------
// Mesh dispatch
// ---------------------------------------------------------------------------

/// Build the [`ParametricMesh`] for `primitive`, validating query parameters
/// and applying the canonical studio defaults for anything the caller did
/// not provide.
pub fn build_mesh(primitive: &str, params: &MeshParams) -> Result<ParametricMesh, MeshServeError> {
    match primitive {
        "sphere" => {
            let radius =
                require_positive("radius", params.radius.unwrap_or(DEFAULT_SPHERE_RADIUS))?;
            let n_lat = require_at_least("n_lat", params.n_lat.unwrap_or(DEFAULT_SPHERE_N_LAT), 2)?;
            let n_lon = require_at_least("n_lon", params.n_lon.unwrap_or(DEFAULT_SPHERE_N_LON), 3)?;
            Ok(sphere_mesh(radius, n_lat, n_lon))
        }
        "plate" => {
            let width = require_positive("width", params.width.unwrap_or(DEFAULT_PLATE_WIDTH))?;
            let height = require_positive("height", params.height.unwrap_or(DEFAULT_PLATE_HEIGHT))?;
            let n_w = require_at_least("n_w", params.n_w.unwrap_or(DEFAULT_PLATE_N_W), 2)?;
            let n_h = require_at_least("n_h", params.n_h.unwrap_or(DEFAULT_PLATE_N_H), 2)?;
            Ok(plate_mesh(width, height, n_w, n_h))
        }
        "cylinder" => {
            let radius = require_positive("radius", params.radius.unwrap_or(DEFAULT_CYL_RADIUS))?;
            let length = require_positive("length", params.length.unwrap_or(DEFAULT_CYL_LENGTH))?;
            let n_circ =
                require_at_least("n_circ", params.n_circ.unwrap_or(DEFAULT_CYL_N_CIRC), 3)?;
            let n_axial =
                require_at_least("n_axial", params.n_axial.unwrap_or(DEFAULT_CYL_N_AXIAL), 2)?;
            Ok(cylinder_mesh(radius, length, n_circ, n_axial))
        }
        "dihedral" => {
            let side = require_positive("side", params.side.unwrap_or(DEFAULT_DIHEDRAL_SIDE))?;
            let n = require_at_least("n", params.n.unwrap_or(DEFAULT_DIHEDRAL_N), 2)?;
            Ok(dihedral_mesh(side, n))
        }
        "trihedral" => {
            let side = require_positive("side", params.side.unwrap_or(DEFAULT_TRIHEDRAL_SIDE))?;
            let n = require_at_least("n", params.n.unwrap_or(DEFAULT_TRIHEDRAL_N), 2)?;
            Ok(trihedral_mesh(side, n))
        }
        other => Err(MeshServeError::UnknownPrimitive(other.to_string())),
    }
}

// ---------------------------------------------------------------------------
// Axum handlers
// ---------------------------------------------------------------------------

pub async fn mesh_list_handler() -> Json<MeshListResponse> {
    Json(MeshListResponse::canonical())
}

pub async fn mesh_stl_handler(
    AxumPath(primitive): AxumPath<String>,
    Query(params): Query<MeshParams>,
) -> Result<Response, MeshServeError> {
    let mesh = build_mesh(&primitive, &params)?;
    let stl = encode_binary_stl(&mesh);
    let mut headers = HeaderMap::new();
    headers.insert(header::CONTENT_TYPE, HeaderValue::from_static("model/stl"));
    headers.insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=300"),
    );
    if let Ok(value) = HeaderValue::from_str(&mesh.primitive_id) {
        headers.insert("x-echoforge-primitive", value);
    }
    if let Ok(value) = HeaderValue::from_str(&mesh.triangle_count().to_string()) {
        headers.insert("x-echoforge-triangle-count", value);
    }
    Ok((StatusCode::OK, headers, stl).into_response())
}

// ---------------------------------------------------------------------------
// Router builder
// ---------------------------------------------------------------------------

/// Sub-router that exposes the mesh-serve endpoints. Designed to be
/// `.merge()`'d into the studio's top-level router (mirrors the
/// `traceability` sub-router pattern).
pub fn mesh_router() -> Router {
    Router::new()
        .route("/api/mesh/list", get(mesh_list_handler))
        .route("/api/mesh/{primitive}", get(mesh_stl_handler))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::Body;
    use axum::http::Request;
    use tower::ServiceExt;

    #[test]
    fn canonical_list_has_five_primitive_ids_in_stable_order() {
        let resp = MeshListResponse::canonical();
        let ids: Vec<&str> = resp
            .primitives
            .iter()
            .map(|p| p.primitive_id.as_str())
            .collect();
        assert_eq!(
            ids,
            vec!["sphere", "plate", "cylinder", "dihedral", "trihedral"]
        );
        for descriptor in &resp.primitives {
            assert!(
                !descriptor.defaults.is_empty(),
                "defaults missing for {}",
                descriptor.primitive_id
            );
        }
    }

    #[test]
    fn build_mesh_applies_defaults_when_params_empty() {
        for primitive in PRIMITIVE_IDS {
            let mesh = match build_mesh(primitive, &MeshParams::default()) {
                Ok(m) => m,
                Err(e) => panic!("primitive {primitive} should build with defaults: {e}"),
            };
            assert_eq!(mesh.primitive_id, primitive);
            assert!(
                mesh.triangle_count() > 0,
                "{primitive} mesh must be non-empty"
            );
            assert!(mesh.all_finite(), "{primitive} mesh must be finite");
        }
    }

    #[test]
    fn build_mesh_rejects_invalid_inputs() {
        let bad_radius = MeshParams {
            radius: Some(0.0),
            ..Default::default()
        };
        assert!(matches!(
            build_mesh("sphere", &bad_radius),
            Err(MeshServeError::InvalidParameter { name: "radius", .. })
        ));

        let bad_n_lon = MeshParams {
            n_lon: Some(2),
            ..Default::default()
        };
        assert!(matches!(
            build_mesh("sphere", &bad_n_lon),
            Err(MeshServeError::InvalidParameter { name: "n_lon", .. })
        ));

        let oversize = MeshParams {
            n_lat: Some(MAX_SAMPLES + 1),
            ..Default::default()
        };
        assert!(matches!(
            build_mesh("sphere", &oversize),
            Err(MeshServeError::InvalidParameter { name: "n_lat", .. })
        ));

        assert!(matches!(
            build_mesh("not_a_primitive", &MeshParams::default()),
            Err(MeshServeError::UnknownPrimitive(_))
        ));
    }

    #[test]
    fn build_mesh_honors_explicit_overrides() {
        let params = MeshParams {
            radius: Some(2.5),
            n_lat: Some(4),
            n_lon: Some(6),
            ..Default::default()
        };
        let mesh = build_mesh("sphere", &params).expect("ok");
        assert_eq!(mesh.dimensions, vec![2.5]);
        // (n_lat - 1) * n_lon * 2 = 3 * 6 * 2 = 36 triangles.
        assert_eq!(mesh.triangle_count(), 36);
    }

    fn rt() -> tokio::runtime::Runtime {
        tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .expect("rt")
    }

    #[test]
    fn list_endpoint_returns_five_primitive_ids() {
        let app = mesh_router();
        let response = rt().block_on(async {
            app.oneshot(
                Request::builder()
                    .uri("/api/mesh/list")
                    .body(Body::empty())
                    .expect("request"),
            )
            .await
            .expect("response")
        });
        assert_eq!(response.status(), StatusCode::OK);
        let body = rt()
            .block_on(async { axum::body::to_bytes(response.into_body(), usize::MAX).await })
            .expect("body");
        let parsed: MeshListResponse = serde_json::from_slice(&body).expect("parse");
        let ids: Vec<String> = parsed
            .primitives
            .into_iter()
            .map(|p| p.primitive_id)
            .collect();
        assert_eq!(
            ids,
            vec![
                "sphere".to_string(),
                "plate".to_string(),
                "cylinder".to_string(),
                "dihedral".to_string(),
                "trihedral".to_string(),
            ]
        );
    }

    #[test]
    fn sphere_endpoint_returns_binary_stl_with_expected_content_type() {
        let app = mesh_router();
        let response = rt().block_on(async {
            app.oneshot(
                Request::builder()
                    .uri("/api/mesh/sphere?radius=1.0")
                    .body(Body::empty())
                    .expect("request"),
            )
            .await
            .expect("response")
        });
        assert_eq!(response.status(), StatusCode::OK);
        let content_type = response
            .headers()
            .get(header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_string();
        assert!(
            content_type.contains("stl") || content_type.contains("octet-stream"),
            "unexpected Content-Type: {content_type}"
        );
        let triangle_header = response
            .headers()
            .get("x-echoforge-triangle-count")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_string();
        let triangle_count: usize = triangle_header.parse().expect("triangle-count header");
        assert!(triangle_count > 0, "triangle count header must be > 0");
        let body = rt()
            .block_on(async { axum::body::to_bytes(response.into_body(), usize::MAX).await })
            .expect("body");
        // Binary STL: 80-byte header + 4-byte count + 50 bytes/tri.
        let expected_len = 84 + triangle_count * 50;
        assert_eq!(body.len(), expected_len, "STL length mismatch");
        // Triangle count word at offset 80..84 must match the header.
        let header_count = u32::from_le_bytes(body[80..84].try_into().expect("4 bytes"));
        assert_eq!(header_count as usize, triangle_count);
    }

    #[test]
    fn unknown_primitive_returns_404() {
        let app = mesh_router();
        let response = rt().block_on(async {
            app.oneshot(
                Request::builder()
                    .uri("/api/mesh/unknown")
                    .body(Body::empty())
                    .expect("request"),
            )
            .await
            .expect("response")
        });
        assert_eq!(response.status(), StatusCode::NOT_FOUND);
        let body = rt()
            .block_on(async { axum::body::to_bytes(response.into_body(), usize::MAX).await })
            .expect("body");
        let value: serde_json::Value = serde_json::from_slice(&body).expect("json");
        assert_eq!(value["error"].as_str(), Some("unknown_primitive"));
    }

    #[test]
    fn invalid_parameter_returns_400() {
        let app = mesh_router();
        let response = rt().block_on(async {
            app.oneshot(
                Request::builder()
                    .uri("/api/mesh/sphere?radius=-1")
                    .body(Body::empty())
                    .expect("request"),
            )
            .await
            .expect("response")
        });
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
        let body = rt()
            .block_on(async { axum::body::to_bytes(response.into_body(), usize::MAX).await })
            .expect("body");
        let value: serde_json::Value = serde_json::from_slice(&body).expect("json");
        assert_eq!(value["error"].as_str(), Some("invalid_parameter"));
    }

    #[test]
    fn all_primitives_round_trip_via_http() {
        let app = mesh_router();
        for primitive in PRIMITIVE_IDS {
            let response = rt().block_on(async {
                app.clone()
                    .oneshot(
                        Request::builder()
                            .uri(format!("/api/mesh/{primitive}"))
                            .body(Body::empty())
                            .expect("request"),
                    )
                    .await
                    .expect("response")
            });
            assert_eq!(
                response.status(),
                StatusCode::OK,
                "primitive {primitive} HTTP status"
            );
            let body = rt()
                .block_on(async { axum::body::to_bytes(response.into_body(), usize::MAX).await })
                .expect("body");
            assert!(
                body.len() > 84,
                "primitive {primitive} STL body too small ({} bytes)",
                body.len()
            );
        }
    }
}
