#!/usr/bin/env python3
"""Generate the runtime code appendix for the EchoForge paper."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "paper" / "source_appendix_manifest.json"
DEFAULT_OUT = REPO_ROOT / "target" / "paper" / "source_appendix" / "source_code_appendix.tex"
DEFAULT_META = REPO_ROOT / "target" / "paper" / "source_appendix" / "source_appendix_metadata.json"

ORIGIN_BACKGROUNDS = {
    "human-origin": "SrcHuman",
    "generated-evolved-origin": "SrcGen",
    "mixed-origin": "SrcMixed",
}


def _tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload if isinstance(payload, dict) else {}


def _symbol_spans(path: Path) -> dict[str, tuple[int, int]]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    spans: dict[str, tuple[int, int]] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            spans[node.name] = (int(node.lineno), int(getattr(node, "end_lineno", node.lineno)))
    return spans


def _extract_symbol(path: Path, symbol: str) -> tuple[int, int, list[str], str]:
    spans = _symbol_spans(path)
    if symbol not in spans:
        raise KeyError(f"{path}: missing symbol {symbol}")
    start, end = spans[symbol]
    lines = path.read_text(encoding="utf-8").splitlines()
    excerpt_lines = lines[start - 1 : end]
    excerpt = "\n".join(excerpt_lines)
    return start, end, excerpt_lines, hashlib.sha256(excerpt.encode("utf-8")).hexdigest()


def _origin_for_relative_line(spans: list[dict[str, Any]], rel_line: int, default: str) -> str:
    for span in spans:
        if int(span.get("start", 0)) <= rel_line <= int(span.get("end", 0)):
            return str(span.get("origin", default))
    return default


def _line_background_option(origins: list[str]) -> str:
    clauses = []
    for line_number, origin in enumerate(origins, start=1):
        color = ORIGIN_BACKGROUNDS.get(origin)
        if color:
            clauses.append(rf"\ifnum\value{{lstnumber}}={line_number}\color{{{color}}}\fi")
    return "linebackgroundcolor={" + "".join(clauses) + "}"


def _emit_codebox(title: str, lines: list[str], *, origins: list[str]) -> str:
    body = "\n".join(lines)
    listing_options = "style=EchoForgePython," + _line_background_option(origins)
    return "\n".join(
        [
            (
                "\\begin{tcolorbox}[enhanced,breakable,"
                f"title={{{_tex_escape(title)}}},colback=CodeBg,colframe=CodeFrame,"
                "fonttitle=\\bfseries\\small]"
            ),
            f"\\begin{{lstlisting}}[{listing_options}]",
            body,
            "\\end{lstlisting}",
            "\\end{tcolorbox}",
        ]
    )


def _symbol_line_origins(
    *,
    line_count: int,
    origin: str,
    spans: list[dict[str, Any]],
) -> list[str]:
    return [_origin_for_relative_line(spans, idx, origin) for idx in range(1, line_count + 1)]


def build(manifest_path: Path, out_path: Path, metadata_path: Path, *, strict: bool) -> None:
    manifest = _read_json(manifest_path)
    chunks = [
        "% Generated by paper/generate_source_appendix.py; do not edit by hand.",
        "\\section{Runtime Code Appendix}",
        (
            "This appendix shows only compact runtime math. Blue blocks are human-origin "
            "baseline code, green blocks are generated/evolved EI code, and lavender "
            "blocks are mixed-origin glue. Repository paths, file writers, paper "
            "plumbing, and CLI wrappers are omitted from the rendered paper.\\par"
        ),
    ]
    metadata_rows: list[dict[str, Any]] = []
    included_block_count = 0
    for block in manifest.get("blocks", []):
        if not isinstance(block, dict):
            continue
        title = str(block.get("title", block.get("id", "Runtime Code")))
        origin = str(block.get("origin", "human-origin"))
        rel_path = str(block.get("path", ""))
        path = REPO_ROOT / rel_path
        if not path.is_file():
            if strict:
                raise FileNotFoundError(path)
            continue

        line_origin_spans = block.get("line_origin_spans", {})
        block_lines: list[str] = []
        block_origins: list[str] = []
        block_metadata: list[dict[str, Any]] = []
        for symbol in [str(item) for item in block.get("symbols", [])]:
            start, end, lines, digest = _extract_symbol(path, symbol)
            spans = line_origin_spans.get(symbol, []) if isinstance(line_origin_spans, dict) else []
            if block_lines:
                block_lines.append("")
                block_origins.append("mixed-origin")
            block_lines.append(f"# {symbol}")
            block_origins.append(origin)
            block_lines.extend(lines)
            block_origins.extend(
                _symbol_line_origins(line_count=len(lines), origin=origin, spans=spans)
            )
            block_metadata.append(
                {
                    "block_id": block.get("id", ""),
                    "title": title,
                    "path": rel_path,
                    "origin": origin,
                    "symbol": symbol,
                    "line_start": start,
                    "line_end": end,
                    "sha256": digest,
                }
            )
        if block_lines:
            chunks.append(f"\\subsection{{{_tex_escape(title)}}}")
            chunks.append(_emit_codebox(title, block_lines, origins=block_origins))
            metadata_rows.extend(block_metadata)
            included_block_count += 1

    out_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    output_text = "\n\n".join(chunks) + "\n"
    tcolorbox_count = output_text.count("\\begin{tcolorbox}")
    listing_count = output_text.count("\\begin{lstlisting}")
    if strict and (tcolorbox_count != included_block_count or listing_count != included_block_count):
        raise AssertionError(
            "source appendix box/listing count mismatch: "
            f"blocks={included_block_count} boxes={tcolorbox_count} listings={listing_count}"
        )
    out_path.write_text(output_text, encoding="utf-8")
    metadata_path.write_text(
        json.dumps(
            {
                "manifest_id": manifest.get("version"),
                "manifest": str(manifest_path.relative_to(REPO_ROOT)),
                "generated_tex": str(out_path.relative_to(REPO_ROOT)),
                "manifest_block_count": included_block_count,
                "tcolorbox_count": tcolorbox_count,
                "listing_count": listing_count,
                "listings": metadata_rows,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}")
    print(f"wrote {metadata_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--metadata", type=Path, default=DEFAULT_META)
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()
    build(args.manifest, args.out, args.metadata, strict=args.strict)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
