#!/usr/bin/env python3
"""Generate the runtime code appendix for the EchoForge paper."""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "paper" / "source_appendix_manifest.json"
DEFAULT_OUT = REPO_ROOT / "target" / "paper" / "source_appendix" / "source_code_appendix.tex"
DEFAULT_META = REPO_ROOT / "target" / "paper" / "source_appendix" / "source_appendix_metadata.json"

ORIGIN_BACKGROUNDS = {
    "human-origin": "SrcHuman",
    "generated-evolved-origin": "SrcGen",
    "mixed-origin": "SrcMixed",
}


def _tex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def _read_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    return payload if isinstance(payload, dict) else {}


def _symbol_spans(path: Path) -> dict[str, tuple[int, int]]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    spans: dict[str, tuple[int, int]] = {}
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            spans[node.name] = (int(node.lineno), int(getattr(node, "end_lineno", node.lineno)))
    return spans


def _extract_symbol(path: Path, symbol: str) -> tuple[int, int, list[str], str]:
    spans = _symbol_spans(path)
    if symbol not in spans:
        raise KeyError(f"{path}: missing symbol {symbol}")
    start, end = spans[symbol]
    lines = path.read_text(encoding="utf-8").splitlines()
    excerpt_lines = lines[start - 1 : end]
    excerpt = "\n".join(excerpt_lines)
    return start, end, excerpt_lines, hashlib.sha256(excerpt.encode("utf-8")).hexdigest()


def _origin_for_relative_line(spans: list[dict[str, Any]], rel_line: int, default: str) -> str:
    for span in spans:
        if int(span.get("start", 0)) <= rel_line <= int(span.get("end", 0)):
            return str(span.get("origin", default))
    return default


def _emit_codebox(title: str, lines: list[str], *, origin: str) -> str:
    color = ORIGIN_BACKGROUNDS.get(origin, "CodeBg")
    body = "\n".join(lines)
    return "\n".join(
        [
            (
                "\\begin{tcolorbox}[enhanced,breakable,"
                f"title={{{_tex_escape(title)}}},colback={color},colframe=CodeFrame,"
                "fonttitle=\\bfseries\\small]"
            ),
            "\\begin{lstlisting}[style=EchoForgePython]",
            body,
            "\\end{lstlisting}",
            "\\end{tcolorbox}",
        ]
    )


def _emit_symbol(
    *,
    symbol: str,
    lines: list[str],
    origin: str,
    spans: list[dict[str, Any]],
) -> str:
    if not spans:
        return _emit_codebox(symbol, lines, origin=origin)

    chunks: list[str] = []
    current_origin = _origin_for_relative_line(spans, 1, origin)
    current_lines: list[str] = []
    for idx, line in enumerate(lines, start=1):
        line_origin = _origin_for_relative_line(spans, idx, origin)
        if line_origin != current_origin and current_lines:
            chunks.append(
                _emit_codebox(f"{symbol} ({current_origin})", current_lines, origin=current_origin)
            )
            current_lines = []
            current_origin = line_origin
        current_lines.append(line)
    if current_lines:
        chunks.append(
            _emit_codebox(f"{symbol} ({current_origin})", current_lines, origin=current_origin)
        )
    return "\n".join(chunks)


def build(manifest_path: Path, out_path: Path, metadata_path: Path, *, strict: bool) -> None:
    manifest = _read_json(manifest_path)
    chunks = [
        "% Generated by paper/generate_source_appendix.py; do not edit by hand.",
        "\\section{Runtime Code Appendix}",
        (
            "This appendix shows only compact runtime math. Blue blocks are human-origin "
            "baseline code, green blocks are generated/evolved EI code, and lavender "
            "blocks are mixed-origin glue. Repository paths, file writers, paper "
            "plumbing, and CLI wrappers are omitted from the rendered paper.\\par"
        ),
    ]
    metadata_rows: list[dict[str, Any]] = []
    for block in manifest.get("blocks", []):
        if not isinstance(block, dict):
            continue
        title = str(block.get("title", block.get("id", "Runtime Code")))
        origin = str(block.get("origin", "human-origin"))
        rel_path = str(block.get("path", ""))
        path = REPO_ROOT / rel_path
        if not path.is_file():
            if strict:
                raise FileNotFoundError(path)
            continue

        chunks.append(f"\\subsection{{{_tex_escape(title)}}}")
        line_origin_spans = block.get("line_origin_spans", {})
        for symbol in [str(item) for item in block.get("symbols", [])]:
            start, end, lines, digest = _extract_symbol(path, symbol)
            spans = line_origin_spans.get(symbol, []) if isinstance(line_origin_spans, dict) else []
            chunks.append(_emit_symbol(symbol=symbol, lines=lines, origin=origin, spans=spans))
            metadata_rows.append(
                {
                    "block_id": block.get("id", ""),
                    "title": title,
                    "path": rel_path,
                    "origin": origin,
                    "symbol": symbol,
                    "line_start": start,
                    "line_end": end,
                    "sha256": digest,
                }
            )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n\n".join(chunks) + "\n", encoding="utf-8")
    metadata_path.write_text(
        json.dumps(
            {
                "version": manifest.get("version"),
                "manifest": str(manifest_path.relative_to(REPO_ROOT)),
                "generated_tex": str(out_path.relative_to(REPO_ROOT)),
                "listings": metadata_rows,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}")
    print(f"wrote {metadata_path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--metadata", type=Path, default=DEFAULT_META)
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()
    build(args.manifest, args.out, args.metadata, strict=args.strict)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
